apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: default
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.m.daocloud.io/kaniko-project/executor:v1.23.2
        args:
        - --context=/workspace
        - --destination=crpi-9jpxgs9322doqt3f.cn-shenzhen.personal.cr.aliyuncs.com/endiow/hello-app:{{GIT_SHORT_HASH}}
        - --destination=crpi-9jpxgs9322doqt3f.cn-shenzhen.personal.cr.aliyuncs.com/endiow/hello-app:latest
        volumeMounts:
        - name: source-pvc
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker
      volumes:
      - name: source-pvc
        persistentVolumeClaim:
          claimName: ci-workspace-pvc
      - name: docker-config
        secret:
          secretName: acr-secret
          items:
          - key: .dockerconfigjson
            path: config.json